"""Foundry fuzz / invariant integration.

Generates Foundry fuzz test suites from confirmed findings and runs them
with `forge test --fuzz-runs N`. This is the property-testing layer: a
static finding says "mint() looks unguarded" — the fuzz test proves it
by throwing random addresses/amounts at the contract and asserting the
invariant that supply never changes from a non-privileged caller.

If forge is not installed, generation still works (tests are written to
disk); execution gracefully reports 'skipped'.
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import Dict, List, Optional

# Attack type → Foundry fuzz test body ({{target}} is the contract address)
FUZZ_TEMPLATES: Dict[str, str] = {
    "mint": """function testFuzz_mint_anyone(uint256 amount) public {
    address attacker = makeAddr("attacker");
    vm.prank(attacker);
    (bool ok,) = address(TARGET).call(
        abi.encodeWithSignature("mint(address,uint256)", attacker, amount)
    );
    // If the call succeeded, an unprivileged account minted - invariant broken.
    assertFalse(ok, "mint() callable by arbitrary account");
}""",
    "initialize": """function testFuzz_initialize_secondCaller(address who) public {
    vm.assume(who != address(0) && who != address(this));
    vm.prank(who);
    (bool ok,) = address(TARGET).call(
        abi.encodeWithSignature("initialize(address)", who)
    );
    // A successful re-initialize means ownership can be stolen.
    assertFalse(ok, "initialize() re-callable - proxy takeover");
}""",
    "withdraw": """function testFuzz_withdraw_amount(uint256 amount) public {
    vm.assume(amount <= 1 ether);
    vm.deal(address(this), amount);
    (bool ok,) = address(TARGET).call(
        abi.encodeWithSignature("withdraw(uint256)", amount)
    );
    // Withdraw from an account with no deposit should fail.
    assertFalse(ok, "withdraw() succeeded with zero balance");
}""",
    "approve": """function testFuzz_approve_anyone(address spender, uint256 amount) public {
    vm.assume(spender != address(0));
    (bool ok,) = address(TARGET).call(
        abi.encodeWithSignature("approve(address,uint256)", spender, amount)
    );
    // If the token approves on behalf of the TESTER without auth - fine.
    // Flag only when the call reverted with a privilege error we don't expect.
    assertTrue(ok, "approve() reverted unexpectedly");
}""",
    "transferOwnership": """function testFuzz_transferOwnership(address newOwner) public {
    vm.assume(newOwner != address(0));
    (bool ok,) = address(TARGET).call(
        abi.encodeWithSignature("transferOwnership(address)", newOwner)
    );
    // Only the current owner may transfer ownership.
    assertFalse(ok, "transferOwnership() callable by non-owner");
}""",
    "oracle": """function testFuzz_oracle_roundtrip(uint256 price) public {
    vm.assume(price > 0 && price < 1e30);
    (bool ok,) = address(TARGET).call(
        abi.encodeWithSignature("setPrice(uint256)", price)
    );
    // Setting an extreme price must not corrupt the contract invariant.
    assertTrue(ok, "price setter reverted");
}""",
}

FUZZ_TEST_HEADER = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";

// Auto-generated by defi-hunter fuzz integration.
// Run: forge test --match-contract Fuzz{TARGET_NAME} --fuzz-runs 1000
contract Fuzz{TARGET_NAME} is Test {{
    address constant TARGET = {TARGET_ADDR};
"""

FUZZ_TEST_FOOTER = "}\n"


def forge_available() -> bool:
    import shutil
    return shutil.which("forge") is not None


def fuzz_test_name(target_addr: str) -> str:
    """Sanitized test contract name from an address."""
    return "Fuzz" + (target_addr[2:6] if len(target_addr) > 6 else "Tgt")


def _unescape_solidity(text: str) -> str:
    """Templates use {{ }} for literal Solidity braces (so they are safe to
    also use with .format()); the generator uses .replace(), so collapse
    {{ -> { and }} -> } before writing."""
    return text.replace("{{", "{").replace("}}", "}")


def generate_fuzz_suite(attack_types: List[str],
                        target_addr: str = "0x0000000000000000000000000000000000000000",
                        out_dir: str = "fuzz") -> Optional[str]:
    """Write a Foundry fuzz test file for the given attack types.

    Returns path to the generated .t.sol file, or None if no templates
    matched.
    """
    matched = [t for t in attack_types if t in FUZZ_TEMPLATES]
    if not matched:
        return None

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    name = fuzz_test_name(target_addr)
    body = _unescape_solidity(
        FUZZ_TEST_HEADER.replace("{TARGET_NAME}", name).replace(
            "{TARGET_ADDR}", target_addr))
    for t in matched:
        body += "\n    " + _unescape_solidity(
            FUZZ_TEMPLATES[t].replace("{TARGET_NAME}", name).replace(
                "{TARGET_ADDR}", target_addr)) + "\n"
    body += FUZZ_TEST_FOOTER

    path = out / f"Fuzz{name}.t.sol"
    path.write_text(body, encoding="utf-8")
    return str(path)


def run_fuzz_suite(test_file: str, fuzz_runs: int = 500,
                   timeout: int = 180, forge_cmd: str = "forge") -> Dict:
    """Run forge fuzz tests on a generated suite; return a result dict.

    Returns {"ok": bool, "ran": bool, "stdout": str, "stderr": str,
             "passed": int, "failed": int}
    """
    if not forge_available():
        return {"ok": False, "ran": False, "stdout": "", "stderr": "",
                "passed": 0, "failed": 0, "reason": "forge not installed"}
    if not os.path.exists(test_file):
        return {"ok": False, "ran": False, "stdout": "", "stderr": "",
                "passed": 0, "failed": 0, "reason": "test file missing"}

    cmd = [forge_cmd, "test", "--match-contract", Path(test_file).stem,
           "--fuzz-runs", str(fuzz_runs)]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True,
                                timeout=timeout, cwd=os.path.dirname(test_file))
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {"ok": False, "ran": False, "stdout": "", "stderr": "",
                "passed": 0, "failed": 0, "reason": "forge timed out or missing"}

    stdout = result.stdout
    passed = stdout.count("[PASS]")
    failed = stdout.count("[FAIL]")
    return {
        "ok": result.returncode == 0,
        "ran": True,
        "stdout": stdout,
        "stderr": result.stderr,
        "passed": passed,
        "failed": failed,
        "reason": "" if result.returncode == 0 else "fuzz tests failed",
    }
